# Generated by Django 5.0 on 2024-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('varieties', models.TextField()),
                ('climate_and_soil_requirements', models.TextField()),
                ('planting_time', models.TextField()),
                ('watering_needs', models.TextField()),
                ('fertilization', models.TextField()),
                ('pest_and_disease_management', models.TextField()),
                ('harvesting_time', models.TextField()),
                ('post_harvest_handling', models.TextField()),
                ('market_information', models.TextField()),
                ('government_schemes_and_subsidies', models.TextField()),
            ],
        ),
    ]
