# Generated by Django 5.0 on 2024-02-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_cropinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinfo',
            name='picture',
            field=models.FileField(blank=True, upload_to='crop_pics'),
        ),
    ]
